### ISSUE TITLE
a/index.html vs b/index.html

### ISSUE THREAD

**Issue by gMan1990** [ahuigo/ahuigo.github.io#2]
- https://ahuigo.github.io/a/index.html
- https://ahuigo.github.io/b/index.html

看起来一样，又不一样 [doge]

**Comment by ahuigo** [comment]
a 的route是ajax 渲染的，对seo不友好。
b 的route是纯静态渲染的，页面是提前generate生成的html，对seo 友好
Update：目前a、b都弃用了

**Comment by gMan1990** [comment]
ok, 我就问问，无意见
